language: ruby
rvm:
  - "1.9.3"
before_install:
#  - gem update --system 2.2.0
#  - gem --version
bundler_args: ''
script:
  - travis_retry cucumber install/install.feature
  - cucumber features
#  - ./check_all_solutions.sh


