# TODO a scaffolded config, it does not yet do anything.
# These files are requires and the autograde won't run without them.
required_files:
  - ruby_intro.rb
# This will search the following directories for required files
# If found, then it will copy the files to the required place.
# Designed to reduce common student mistakes.
search_paths:
  - hw-ruby-intro/
  - lib/
  - hw-ruby-intro/lib/
